In [ ]:
import pandas as pd
dff=pd.read_csv("/content/hr_interview_questions_cleaned.csv")

In [ ]:
OUTPUT_FILE = "/content/unique_questions_answers.csv"
# Remove duplicate questions
df_unique = dff.drop_duplicates(
    subset="question",
    keep="first"
)

# Keep ONLY question and answer
df_unique = df_unique[["question", "ideal_answer"]]

# Save
df_unique.to_csv(OUTPUT_FILE, index=False)

In [ ]:
df=pd.read_csv("/content/unique_questions_answers.csv")
df

,question,ideal_answer
0,Tell me about a time you had to learn somethin...,I'm always eager to learn and embrace change a...
1,Describe a time you handled a difficult situat...,"When faced with conflict, I approach it calmly..."
2,Where do you see yourself in 5 years?,My long-term goal is to grow into a senior rol...
3,Tell me about a conflict you had with a cowork...,"When faced with conflict, I approach it calmly..."
4,What skills do you hope to develop in your nex...,My long-term goal is to grow into a senior rol...
5,What's the most significant change you've had ...,I'm always eager to learn and embrace change a...
6,How does this role fit into your career path?,My long-term goal is to grow into a senior rol...
7,Tell me about a time you worked well within a ...,I believe communication and mutual respect are...
8,What are your expectations from leadership in ...,"I thrive in collaborative, transparent environ..."
9,What motivates you to come to work every day?,I'm motivated by challenges and the opportunit...
10,How do you motivate others in a leadership role?,I lead by example and encourage open communica...
11,What tools or methods help you stay organized?,I follow a structured workflow and use tools l...
12,How do you build trust with new teammates?,I believe communication and mutual respect are...
13,Describe a time you felt out of place in a wor...,"I thrive in collaborative, transparent environ..."
14,Do you prefer working independently or in team...,I follow a structured workflow and use tools l...
15,Describe a time you led a project or team.,I lead by example and encourage open communica...
16,How do you delegate tasks effectively?,I lead by example and encourage open communica...
17,How do you align with our company values?,"I thrive in collaborative, transparent environ..."
18,Why do you want to work at our company?,I'm motivated by challenges and the opportunit...
19,What makes a good leader in your opinion?,I lead by example and encourage open communica...
20,What are your long-term career aspirations?,My long-term goal is to grow into a senior rol...
21,Describe your ideal workday.,I follow a structured workflow and use tools l...
22,How do you deal with feedback that you disagre...,"When faced with conflict, I approach it calmly..."
23,What role do you usually play in group settings?,I believe communication and mutual respect are...
24,What would you do if you disagreed with your m...,"When faced with conflict, I approach it calmly..."
25,Tell me about a time you were highly motivated...,I'm motivated by challenges and the opportunit...
26,How do you contribute to a positive team envir...,"I thrive in collaborative, transparent environ..."
27,What drives your passion for this field?,I'm motivated by challenges and the opportunit...
28,How do you react to sudden changes in priorities?,I'm always eager to learn and embrace change a...
29,How do you respond when a teammate isn't pulli...,"When faced with conflict, I approach it calmly..."
30,Tell me about a time you mentored someone.,I lead by example and encourage open communica...
31,How do you ensure productivity when working re...,I follow a structured workflow and use tools l...
32,How do you stay motivated during repetitive ta...,I'm motivated by challenges and the opportunit...
33,How do you organize and prioritize your daily ...,I follow a structured workflow and use tools l...
34,What type of company culture do you thrive in?,"I thrive in collaborative, transparent environ..."
35,How do you handle disagreements within a team?,I believe communication and mutual respect are...
36,Describe a project where teamwork was essentia...,I believe communication and mutual respect are...
37,Describe a time you failed and what you learne...,I'm always eager to learn and embrace change a...
38,How do you stay updated with industry trends?,I'm always eager to learn and embrace change a...
39,What kind of growth opportunities are you look...,My long-term goal is to grow into a senior rol...

In [ ]:
dff=dff.drop(columns=['category','experience','source_type','difficulty'])

In [ ]:
dff

,question,role,ideal_answer
0,Tell me about a time you had to learn somethin...,DevOps Engineer,I'm always eager to learn and embrace change a...
1,Describe a time you handled a difficult situat...,Product Manager,"When faced with conflict, I approach it calmly..."
2,Where do you see yourself in 5 years?,Data Scientist,My long-term goal is to grow into a senior rol...
3,Tell me about a conflict you had with a cowork...,Marketing Associate,"When faced with conflict, I approach it calmly..."
4,What skills do you hope to develop in your nex...,Marketing Associate,My long-term goal is to grow into a senior rol...
...,...,...,...
740257,Describe a project where teamwork was essentia...,HR Specialist,I believe communication and mutual respect are...
740258,What's the most significant change you've had ...,UX Designer,I'm always eager to learn and embrace change a...
740259,How do you stay motivated during repetitive ta...,UX Designer,I'm motivated by challenges and the opportunit...
740260,What role do you usually play in group settings?,Marketing Associate,I believe communication and mutual respect are...
740261,Describe your ideal workday.,UX Designer,I follow a structured workflow and use tools l...

In [ ]:

print("Before:", len(dff))
print("Duplicate rows:", dff.duplicated().sum())

df = dff.drop_duplicates().reset_index(drop=True)

print("After:", len(df))

Before: 740262
Duplicate rows: 739942
After: 320

In [ ]:
df.duplicated()
df

,question,role,ideal_answer
0,Tell me about a time you had to learn somethin...,DevOps Engineer,I'm always eager to learn and embrace change a...
1,Describe a time you handled a difficult situat...,Product Manager,"When faced with conflict, I approach it calmly..."
2,Where do you see yourself in 5 years?,Data Scientist,My long-term goal is to grow into a senior rol...
3,Tell me about a conflict you had with a cowork...,Marketing Associate,"When faced with conflict, I approach it calmly..."
4,What skills do you hope to develop in your nex...,Marketing Associate,My long-term goal is to grow into a senior rol...
...,...,...,...
315,What motivates you to come to work every day?,Product Manager,I'm motivated by challenges and the opportunit...
316,Describe a time you handled a difficult situat...,QA Analyst,"When faced with conflict, I approach it calmly..."
317,Where do you see yourself in 5 years?,HR Specialist,My long-term goal is to grow into a senior rol...
318,Tell me about a time you had to learn somethin...,Product Manager,I'm always eager to learn and embrace change a...
319,How do you contribute to a positive team envir...,Data Scientist,"I thrive in collaborative, transparent environ..."

In [ ]:
OUTPUT_FILE = "/content/udpate_questions_answers.csv"
df.to_csv(OUTPUT_FILE,index=False)

In [ ]:
d=pd.read_csv("/content/udpate_questions_answers.csv")
d

,question,role,ideal_answer
0,Tell me about a time you had to learn somethin...,DevOps Engineer,I'm always eager to learn and embrace change a...
1,Describe a time you handled a difficult situat...,Product Manager,"When faced with conflict, I approach it calmly..."
2,Where do you see yourself in 5 years?,Data Scientist,My long-term goal is to grow into a senior rol...
3,Tell me about a conflict you had with a cowork...,Marketing Associate,"When faced with conflict, I approach it calmly..."
4,What skills do you hope to develop in your nex...,Marketing Associate,My long-term goal is to grow into a senior rol...
...,...,...,...
315,What motivates you to come to work every day?,Product Manager,I'm motivated by challenges and the opportunit...
316,Describe a time you handled a difficult situat...,QA Analyst,"When faced with conflict, I approach it calmly..."
317,Where do you see yourself in 5 years?,HR Specialist,My long-term goal is to grow into a senior rol...
318,Tell me about a time you had to learn somethin...,Product Manager,I'm always eager to learn and embrace change a...
319,How do you contribute to a positive team envir...,Data Scientist,"I thrive in collaborative, transparent environ..."

In [ ]:
dff = d.duplicated(
    subset=['question', 'ideal_answer', 'role'],
    keep='first'
).reset_index(drop=True)
dff

0      False
1      False
2      False
3      False
4      False
       ...
315    False
316    False
317    False
318    False
319    False
Length: 320, dtype: bool